# Generated by Django 5.2.1 on 2025-05-18 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='downvoters',
            field=models.ManyToManyField(related_name='downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='link',
            name='upvoters',
            field=models.ManyToManyField(related_name='upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
