# Generated by Django 5.2.1 on 2025-05-19 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_link_downvoters_link_upvoters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='downvoters',
            field=models.ManyToManyField(blank=True, null=True, related_name='downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='upvoters',
            field=models.ManyToManyField(blank=True, null=True, related_name='upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
